version: '3'

volumes:
  opensearch-data1:
  opensearch-data2:
  fluentd-log:

networks:
  opensearch-net:

# refer to https://opensearch.org/docs/latest/opensearch/install/docker/
services:
  # https://opensearch.org/docs/latest/opensearch/install/important-settings
  # increase max_map_count to fix the issue that vm.max_map_count is too low.
  # sysctl -w vm.max_map_count=262144
  # echo "vm.max_map_count=262144" >> /etc/sysctl.conf
  opensearch-node1:
    image: opensearchproject/opensearch:2
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      # below settings required for cluster
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      # uncomment below to disable security and deploy single node in development env
      # - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      # - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      # - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:2
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    ports:
      - 5600:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net

  # fluentd for log aggregate
  fluentd-server:
    image: fluentd-server
    build: ./fluentd
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluent.conf
      - fluentd-log:/fluentd/log
    networks:
      - opensearch-net
    ports:
      - 24224:24224
      - 24224:24224/udp
    expose:
      - "24224"

  # https://github.com/openzipkin/zipkin/issues/3430
  # use opensearch by setting `persistent.compatibility.override_main_response_version` to true
  # PUT _cluster/settings
  # {
  #  "persistent": {
  #    "compatibility": {
  #    "override_main_response_version": true
  #     }
  #   }
  # }
  zipkin-server:
    image: openzipkin/zipkin-slim
    networks:
      - opensearch-net
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: https://opensearch-node1:9200
      ES_USERNAME: admin
      ES_PASSWORD: admin
      # https://github.com/openzipkin/zipkin/pull/3100
      ES_SSL_NO_VERIFY: "true"
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O/dev/null", "http://localhost:9411/health" ]

  # TODO OpenSearch SSL issue?
  # https://github.com/apache/skywalking/tree/master/docker
  skywalking-server:
    image: apache/skywalking-oap-server:9.1.0
    networks:
      - opensearch-net
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl health" ]
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      SW_HEALTH_CHECKER: default
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: opensearch-node1:9200,opensearch-node2:9200
      SW_STORAGE_ES_HTTP_PROTOCOL: https
      SW_ES_USER: admin
      SW_ES_PASSWORD: admin
      SW_STORAGE_ES_SSL_JKS_PATH: /var/opensearch.jks
      SW_STORAGE_ES_SSL_JKS_PASS: "a123456"
      # receiver-zipkin just store rather than analyze zipkin traces.
      # SW_RECEIVER_ZIPKIN: default

  skywalking-ui:
    image: apache/skywalking-ui:9.1.0
    networks:
      - opensearch-net
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://skywalking-server:12800