version: '3.6'
volumes:
  fluent-bit-data:
  
services:
  # just parse and forward logs to fluentd
  fluent-bit:
    image: chuntungho/fluent-bit-docker
    volumes:
      - fluent-bit-data:/fluent-bit/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    command:
      - -c 
      - /fluent-bit/etc/fluent-bit.conf
      # just forward to fluentd-server
      - -o
      - 'forward://<fluentd-server-ip>:24224'
      # uncomment below to use in development env
      # - -o opensearch
      # - -p Host=opensearch-node1
      # - -p Logstash_Format=true
      # - -p Logstash_Prefix=fluent-bit
      # - -p Suppress_Type_Name=On
    networks:
      - apm-net
    deploy:
      mode: global
    logging:
      driver: "json-file"
      options:
        max-size: "64m"
        max-file: "8"
