# Static configuration
# https://doc.traefik.io/traefik/v3.0/providers/overview/
providers:
  docker:
    # for local test
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  file:
    # form default cert
    filename: /etc/traefik/dynamic.yml

# API and dashboard configuration
api:
  insecure: true

certificatesResolvers:
  myresolver:
    acme:
      email: youremail@email.com
      # default acme.json
      storage: /acme/acme.json
      # https://doc.traefik.io/traefik/https/acme/#dnschallenge
      # cloudflare dns challenge
      dnsChallenge:
        provider: cloudflare
        #resolvers:
        #  - 1.1.1.1:53

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: myresolver