# Docker configuration backend
providers:
  docker:
    # for local test
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
  insecure: true

certificatesResolvers:
  myresolver:
    acme:
      email: youremail@email.com
      # default acme.json
      storage: /acme/acme.json
      # https://doc.traefik.io/traefik/https/acme/#dnschallenge
      # cloudflare dns challenge
      dnsChallenge:
        provider: cloudflare

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: myresolver

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: myresolver
        domain:
          main: example.org
          sans:
            - foo.example.org
            - bar.example.org
