version: "3.8"

volumes:
  acme:
  
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)
      - traefik.http.routers.traefik.service=traefik@docker
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      # cloudflare wildcard cert config
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/:/etc/traefik/
      - acme:/acme # for saving cert key
   
  whoami:
    image: traefik/whoami
    # target host: whoami.docker.localhost
    container_name: whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)