version: "3.8"

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:traefik.docker.localhost"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.port: 8080
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      # cloudflare wildcard cert config
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/traefik.yml:/etc/traefik/traefik.yml
      - ./conf/acme.json:/etc/acme.json  # for saving cert key
   
  whoami:
    image: traefik/whoami
    # target host: whoami.docker.localhost
    container_name: whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)