version: '3.6'

volumes:
  rabbitmq-dev-data:

services:
  # rabbitmq for dev
  rabbitmq:
    #image: rabbitmq:3.8-management
    image: middleware/rabbitmq:3.8-custom
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rabbit-dev
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      #RABBITMQ_DEFAULT_USER: admin
      #RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_NODENAME: rabbit@rabbit-dev
      RABBITMQ_ERLANG_COOKIE: cluster-secret-cookie
    volumes:
      - rabbitmq-dev-data:/var/lib/rabbitmq