version: '3.6'

# Note that network should be attachable which will be attached to docker compose
# docker network create --driver overlay --attachable consul-net
networks:
  consul-net:
    external: true

volumes:
  consul-data:

# comment configs when deployed by portainer
configs:
  git2consul-conf:
    file: ./config/git2consul.json
  webui-conf:
    file: ./config/consul-webui.conf
  htpasswd-conf:
    file: ./config/consul-auth.htpasswd

# deploy consul server on each nodes by node label
# https://stackoverflow.com/questions/54220374/consul-on-docker-swarm-with-spring-boot-clients
services:
  # ports: 8500
  consul-peer-a: &consul-peer
    image: "consul:1.13"
    networks:
      consul-net:
        aliases:
          - consul-server
    environment:
      CONSUL_BIND_INTERFACE: eth0
      # https://www.consul.io/docs/agent/options
      CONSUL_LOCAL_CONFIG: '{"server": true,"bootstrap_expect": 3, "client_addr": "0.0.0.0", "disable_update_check": true}'
    command: [ "agent", "-node", "consul-peer-a", "-retry-join", "consul-peer-b", "-retry-join", "consul-peer-c" ]
    volumes:
      - consul-data:/consul/data
    deploy:
      placement:
        constraints:
          - "node.labels.consul-peer-name==consul-peer-a"

  consul-peer-b:
    <<: *consul-peer
    command: [ "agent", "-node", "consul-peer-b", "-retry-join", "consul-peer-a","-retry-join", "consul-peer-c" ]
    deploy:
      placement:
        constraints:
          - "node.labels.consul-peer-name==consul-peer-b"

  # enable web ui just for this peer
  consul-peer-c:
    <<: *consul-peer
    command: [ "agent", "-ui", "-node", "consul-peer-c", "-retry-join", "consul-peer-a","-retry-join", "consul-peer-b" ]
    deploy:
      placement:
        constraints:
          - "node.labels.consul-peer-name==consul-peer-c"

  # proxy to ui peer with basic auth
  web-ui:
    image: nginx:alpine
    networks:
      - consul-net
    ports:
      - "18500:8500"
    # comment configs when deployed by portainer
    configs:
      - source: webui-conf
        target: /etc/nginx/conf.d/consul.conf
      - source: htpasswd-conf
        target: /etc/nginx/.htpasswd

  git2consul-go:
    image: chuntungho/git2consul-go
    networks:
      - consul-net
    command: ["-config", "/etc/git2consul.json", "-debug"]
    # comment configs when deployed by portainer
    configs:
      - source: git2consul-conf
        target: /etc/git2consul.json
    deploy:
      placement:
        constraints:
          - "node.role == manager"