version: '3.6'

services:
  ingress:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "64m"
        max-file: "8"