global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    # enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  # enable_http2: true
  static_configs:
  - targets:
    - localhost:9090

# grafana: Node Exporter Full (1860)
- job_name: node
  proxy_url: http://proxy-host:13128
  static_configs:
   - targets:
     - node-ip:9100

# grafana: MySQL Overview (7362)
- job_name: mysql
  proxy_url: http://proxy-host:13128
  static_configs:
    - targets:
      - server1-ip:3306
      - server2-ip:3306
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      # The mysqld_exporter host:port
      replacement: mysqld-exporter:19104

# grafana: RabbitMQ-Overview (10991)
- job_name: 'rabbitmq'
  proxy_url: http://proxy-host:13128
  static_configs:
    - targets: ['rabbit-peer-a:15692', 'rabbit-peer-b:15692', 'rabbit-peer-c:15692']

# grafana: Redis Dashboard (763) 
## config for scraping the exporter itself
- job_name: 'redis_exporter'
  static_configs:
  - targets:
    - redis-exporter:9121

## config for the multiple Redis targets that the exporter will scrape
- job_name: 'redis_exporter_targets'
  static_configs:
  - targets:
    - redis://redis-node1:6001
    - redis://redis-node1:6002
    - redis://redis-node2:6001
    - redis://redis-node2:6002
    - redis://redis-node3:6001
    - redis://redis-node3:6002
  metrics_path: /scrape
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: redis-exporter:9121

# grafana: JVM (micrometer) (4701)
- job_name: backend_services
  proxy_url: http://proxy-host:13128
  consul_sd_configs:
    - server: consul-server:8500
      proxy_url: http://proxy-host:13128
  relabel_configs:
    - source_labels: [__meta_consul_service]
      separator: ;
      regex: (.*)
      target_label: application
      replacement: $1
      action: replace
    - source_labels: [__metrics_path__]
      separator: ;
      regex: /metrics
      target_label: __metrics_path__
      replacement: /actuator/prometheus
      action: replace
    - source_labels: ['__meta_consul_tags']
      regex: '^.*,management,.*$'
      action: keep

# grafana: NGINX exporter (12708)
- job_name: nginx
  static_configs:
  - targets: ['nginx-exporter:9113']

- job_name: cadvisor
  static_configs:
  - targets: ['cadvisor:8080']
