version: '3'

volumes:
  ds_data:

services:
  # https://hub.docker.com/r/openmicroscopy/apacheds
  ldap-server:
    image: openmicroscopy/apacheds
    ports:
      - '10389:10389'
    volumes:
      - 'ds_data:/var/lib/apacheds'