version: '3.8'

# https://hub.docker.com/_/mysql
services:
  mysql8:
    image: mysql:8.0.35
    # before initialization for mysql 8
    command: --lower-case-table-names=1
    container_name: mysql8
    volumes:
      - ${HOME}/data/mysql8.0:/var/lib/mysql/
      - ./my8.0.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      # set root host for mysql 8
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
    # only start when --profile=newer
    profiles: ["newer"]

  mysql5:
    image: mysql:5.7
    command: --lower-case-table-names=1
    container_name: mysql5
    volumes:
      - ${HOME}/data/mysql5.7:/var/lib/mysql/
      - ./my5.7.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "TZ=Asia/Shanghai"
    ports:
      - 3305:3306