version: '3.8'

services:
  # https://hub.docker.com/_/postgres
  # https://hub.docker.com/r/dimitri/pgloader
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/data/postgres:/var/lib/postgresql/data